<a href="https://colab.research.google.com/github/muhammadibrohimovDEV/Pandas-library/blob/main/Tartiblash_(sorting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

In [25]:
obj = pd.Series(range(4) , index = ['d' , 'a' , 'b' , 'c'])

In [26]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [27]:
obj.sort_index() # .sort_index() Seriesni index lari bo'yicha tartiblaydi

a    1
b    2
c    3
d    0
dtype: int64

In [28]:
obj.sort_values() # .sort_values() Series ni qiymatlari bo'yicha tartiblaydi

d    0
a    1
b    2
c    3
dtype: int64

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv' , index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [30]:
df.sort_index() # DataFrame ni indexlari bo'yicha tartiblaydi(axis = 0)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [31]:
df.sort_index(axis = 1) # DataFrame ni ustunlari bo'yicha tartiblaydi (axis = 1 , inplace = True)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [32]:
df.sort_index(axis = 1 , inplace = True , ascending = False) # ascending = False bu teskari tartiblah (yuqoridan , pastga)

In [33]:
df

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan

In [34]:
df.sort_index(ascending = False)

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
...,...,...,...,...,...,...,...,...,...,...,...,...
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota

In [42]:
df.sort_values(by = 'price' , ascending = False , inplace = True)
df

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
502,2017,wddjk7ea3hf044968,clean vehicle,florida,84900,sl-class,25302,167607883,usa,2 days left,silver,mercedes-benz
1340,2019,1ft8w4dt6ked32656,clean vehicle,illinois,74000,drw,10536,167780682,usa,2 days left,no_color,ford
1336,2019,1ft8w3dt3kee48276,clean vehicle,illinois,70000,drw,9643,167780680,usa,2 days left,no_color,ford
277,2019,2c3cdzl97kh518237,clean vehicle,ohio,67000,challenger,10944,167759490,usa,21 hours left,blue,dodge
1215,2019,1ft7w2bt0kec44818,clean vehicle,indiana,65500,srw,6500,167718954,usa,21 hours left,black,ford
...,...,...,...,...,...,...,...,...,...,...,...,...
330,1996,1falp62w5th144314,salvage insurance,california,0,door,296860,167359712,usa,19 hours left,green,ford
370,1997,1ftdf18w8vna61251,salvage insurance,wisconsin,0,door,146912,167362449,usa,2 days left,green,ford
400,2006,2g4wc582961163677,salvage insurance,virginia,0,door,137464,167651221,usa,9 days left,blue,buick
297,2003,1hgcm56363a030975,salvage insurance,arkansas,0,door,152608,167552893,usa,17 hours left,white,honda
354,2009,1ftyr10d19pa60391,salvage insurance,tennessee,0,pickup,180364,167360535,usa,2 days left,blue,ford

In [44]:
df.sort_values(by = ['price' , 'mileage'])

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
545,1993,1gkfk16k5pj701631,salvage insurance,colorado,0,door,0,167358601,usa,18 hours left,light blue,gmc
309,2004,3gnek12t74g240524,salvage insurance,wyoming,0,door,0,167418651,usa,18 hours left,maroon,chevrolet
322,1994,1fdee14n7rha47894,salvage insurance,california,0,chassis,0,167359174,usa,19 hours left,green,ford
349,2009,5sfgf29269e031344,clean vehicle,pennsylvania,0,sundance,1,167266321,usa,7 days left,white,heartland
196,2017,1fbax2cv0hkb32599,clean vehicle,texas,0,mpv,76858,167656523,usa,2 days left,white,ford
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,2019,1ft7w2bt0kec44818,clean vehicle,indiana,65500,srw,6500,167718954,usa,21 hours left,black,ford
277,2019,2c3cdzl97kh518237,clean vehicle,ohio,67000,challenger,10944,167759490,usa,21 hours left,blue,dodge
1336,2019,1ft8w3dt3kee48276,clean vehicle,illinois,70000,drw,9643,167780680,usa,2 days left,no_color,ford
1340,2019,1ft8w4dt6ked32656,clean vehicle,illinois,74000,drw,10536,167780682,usa,2 days left,no_color,ford
502,2017,wddjk7ea3hf044968,clean vehicle,florida,84900,sl-class,25302,167607883,usa,2 days left,silver,mercedes-benz